### ISSUE TITLE
Alternative method with feh

### ISSUE THREAD

**Issue by TechnologyClassroom** [lee2sman/rasp-pi-slideshow#3]
Thanks for the follow!  I checked out some of your projects.  I have done something similar to this with the Raspberry Pi.  It only depends on feh for photos and omxplayer for videos

My code is at https://github.com/TechnologyClassroom/bash/blob/master/BlueHillTV.sh

**Comment by lee2sman** [comment]
Thanks! This is great.

**Comment by TechnologyClassroom** [comment]
You're welcome!  Thanks!
