### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by anohren** [lee2sman/rasp-pi-slideshow#4]
Thanks for sharing. 

I first tried making this using a systemd service with both fbi and fim, but never found a single working solution either online or by myself. Neither slideshow nor user interaction worked. I could probably have read up on systemd unit files, session management, virtual terminals and the frame buffer for a week and still not have come close to a solution. Never imagined it would be such a complex task...

This worked first try with `fim`, within five minutes. 

I no longer care about the lost "learning opportunity" with systemd.

**Comment by lee2sman** [comment]
Great to hear!
